// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_de_practicas.Data;

#nullable disable

namespace Proyecto_de_practicas.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20251121143001_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_de_practicas.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("TipoArticuloId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoArticuloId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.ArticuloCampoValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("CampoArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("CampoArticuloId");

                    b.ToTable("ArticuloCamposValores");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.CampoArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoArticuloId");

                    b.ToTable("CamposArticulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.TipoArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImagenPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoArticulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.TipoUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUbicacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Traslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaTraslado")
                        .HasColumnType("datetime2");

                    b.Property<int>("UbicacionDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionOrigenId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UbicacionDestinoId");

                    b.HasIndex("UbicacionOrigenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Traslado");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<int>("TipoUbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoUbicacionId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Nombre = "Artículos",
                            Ruta = "/articulos"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Nombre = "Ubicaciones",
                            Ruta = "/ubicaciones"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            Nombre = "Traslados",
                            Ruta = "/traslados"
                        },
                        new
                        {
                            Id = 4,
                            Estado = 1,
                            Nombre = "Inventario",
                            Ruta = "/inventario"
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            Nombre = "Reportes",
                            Ruta = "/reportes"
                        },
                        new
                        {
                            Id = 6,
                            Estado = 1,
                            Nombre = "Seguridad",
                            Ruta = "/seguridad"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Crear"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Editar"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Ver"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Eliminar"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.RolSubModuloPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("RolSubModuloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolSubModuloId");

                    b.ToTable("RolSubModuloPermisos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("SubModulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            ModuloId = 1,
                            Nombre = "Artículos",
                            Ruta = "/articulos/lista"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            ModuloId = 1,
                            Nombre = "Tipos de Artículo",
                            Ruta = "/articulos/tipos"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            ModuloId = 2,
                            Nombre = "Ubicaciones",
                            Ruta = "/ubicaciones/lista"
                        },
                        new
                        {
                            Id = 4,
                            Estado = 1,
                            ModuloId = 2,
                            Nombre = "Tipos de Ubicación",
                            Ruta = "/ubicaciones/tipos"
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            ModuloId = 6,
                            Nombre = "Usuarios",
                            Ruta = "/seguridad/usuarios"
                        },
                        new
                        {
                            Id = 6,
                            Estado = 1,
                            ModuloId = 6,
                            Nombre = "Roles",
                            Ruta = "/seguridad/roles"
                        },
                        new
                        {
                            Id = 7,
                            Estado = 1,
                            ModuloId = 6,
                            Nombre = "Permisos",
                            Ruta = "/seguridad/permisos"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Security.RolSubModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("SubModuloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("SubModuloId");

                    b.ToTable("RolSubmodulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Articulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Models.TipoArticulo", "TipoArticulo")
                        .WithMany("Articulos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Models.Ubicacion", "Ubicacion")
                        .WithMany("Articulos")
                        .HasForeignKey("UbicacionId");

                    b.Navigation("TipoArticulo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.ArticuloCampoValor", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Models.CampoArticulo", "CampoArticulo")
                        .WithMany()
                        .HasForeignKey("CampoArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("CampoArticulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.CampoArticulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Models.TipoArticulo", "TipoArticulo")
                        .WithMany("Campos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoArticulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Inventario", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Models.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Traslado", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Models.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("UbicacionDestinoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Models.Ubicacion", "UbicacionOrigen")
                        .WithMany()
                        .HasForeignKey("UbicacionOrigenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("UbicacionDestino");

                    b.Navigation("UbicacionOrigen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Ubicacion", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Models.TipoUbicacion", "TipoUbicacion")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("TipoUbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUbicacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.RolSubModuloPermiso", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Permiso", "Permiso")
                        .WithMany("RolSubModuloPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Security.RolSubModulo", "RolSubModulo")
                        .WithMany("Permisos")
                        .HasForeignKey("RolSubModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("RolSubModulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Modulo", "Modulo")
                        .WithMany("SubModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Usuario", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Security.RolSubModulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("SubModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.TipoArticulo", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Campos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.TipoUbicacion", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Models.Ubicacion", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Modulo", b =>
                {
                    b.Navigation("SubModulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Permiso", b =>
                {
                    b.Navigation("RolSubModuloPermisos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Security.RolSubModulo", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
