// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_de_practicas.Data;

#nullable disable

namespace Proyecto_de_practicas.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20260601010512_InitialUbicacionnn")]
    partial class InitialUbicacionnn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBarra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPatrimonial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAdquision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HDeprAjustada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HDeprEjercicio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HDeprInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HValorInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mayor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medidas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCodeBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoArticuloId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.Property<double>("ValorAdquisitivo")
                        .HasColumnType("float");

                    b.Property<decimal>("ValorNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VidaUtil")
                        .HasColumnType("int")
                        .HasColumnName("vidaUtil");

                    b.HasKey("Id");

                    b.HasIndex("TipoArticuloId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("articulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.ArticuloCampoValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("CampoArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("CampoArticuloId");

                    b.ToTable("ArticuloCamposValores");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoArticuloId");

                    b.ToTable("CamposArticulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.EncabezadoResult", b =>
                {
                    b.Property<string>("Encabezado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EncabezadoResult");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Prestamos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoPrestamo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImagenPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoArticulos");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Descripcion = "Otros",
                            Estado = 1,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Mantenimiento.Entity.Mantenimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoMantenimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorServicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Icon = "fa-solid fa-home",
                            Nombre = "Dashboard",
                            Ruta = "/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Icon = "fa-solid fa-box",
                            Nombre = "Artículos",
                            Ruta = "/articulos"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            Icon = "fa-solid fa-map-marker-alt",
                            Nombre = "Ubicaciones",
                            Ruta = "/ubicaciones"
                        },
                        new
                        {
                            Id = 4,
                            Estado = 1,
                            Icon = "fa-solid fa-exchange-alt",
                            Nombre = "Traslados",
                            Ruta = "/traslados"
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            Icon = "fa-solid fa-handshake",
                            Nombre = "Prestamos",
                            Ruta = "/prestamos"
                        },
                        new
                        {
                            Id = 6,
                            Estado = 1,
                            Icon = "fa-solid fa-screwdriver-wrench",
                            Nombre = "Mantenimiento",
                            Ruta = "/mantenimiento"
                        },
                        new
                        {
                            Id = 7,
                            Estado = 1,
                            Icon = "fa-solid fa-chart-line",
                            Nombre = "Reportes",
                            Ruta = "/reportes"
                        },
                        new
                        {
                            Id = 8,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            Nombre = "Seguridad",
                            Ruta = "/seguridad"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Crear"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Editar"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Ver"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Eliminar"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("SubModulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Icon = "fa-solid fa-box-open",
                            ModuloId = 2,
                            Nombre = "Artículos",
                            Ruta = "/articulos"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Icon = "fa-solid fa-tags",
                            ModuloId = 2,
                            Nombre = "Tipos de Artículo",
                            Ruta = "/tipos-articulos"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            Icon = "fa-solid fa-map-marker",
                            ModuloId = 3,
                            Nombre = "Ubicaciones",
                            Ruta = "/ubicaciones"
                        },
                        new
                        {
                            Id = 4,
                            Estado = 1,
                            Icon = "fa-solid fa-layer-group",
                            ModuloId = 3,
                            Nombre = "Tipos de Ubicación",
                            Ruta = "/tipo-ubicacion"
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            Icon = "fa-solid fa-user",
                            ModuloId = 8,
                            Nombre = "Usuarios",
                            Ruta = "/usuarios"
                        },
                        new
                        {
                            Id = 6,
                            Estado = 1,
                            Icon = "fa-solid fa-user-shield",
                            ModuloId = 8,
                            Nombre = "Roles",
                            Ruta = "/roles"
                        },
                        new
                        {
                            Id = 7,
                            Estado = 1,
                            Icon = "fa-solid fa-key",
                            ModuloId = 8,
                            Nombre = "Permisos",
                            Ruta = "/permisos"
                        },
                        new
                        {
                            Id = 8,
                            Estado = 1,
                            Icon = "fa-solid fa-layer-group",
                            ModuloId = 8,
                            Nombre = "Modulos",
                            Ruta = "/modulos"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Security.RolPermisos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int?>("SubModuloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.HasIndex("SubModuloId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 6,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 7,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 8,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 9,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 10,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 11,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 12,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 13,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 14,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 15,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 16,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 17,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 18,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 19,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 20,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 21,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 22,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 23,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 24,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 25,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 26,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 27,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 28,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 29,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 30,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 31,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 32,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 33,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 34,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 35,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 36,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 4
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Traslados.Entities.Traslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaTraslado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UbicacionDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionOrigenId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UbicacionDestinoId");

                    b.HasIndex("UbicacionOrigenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Traslado");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.TipoUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUbicacion");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Descripcion = "General",
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PadreId")
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<int>("TipoUbicacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PadreId");

                    b.HasIndex("TipoUbicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ubicaciones");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Descripcion = "Ubicación por defecto para artículos sin ubicación especificada",
                            Nombre = "Otros",
                            Piso = 0,
                            TipoUbicacionId = 100
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", "TipoArticulo")
                        .WithMany("Articulos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Articulos")
                        .HasForeignKey("UbicacionId");

                    b.Navigation("TipoArticulo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.ArticuloCampoValor", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", "CampoArticulo")
                        .WithMany("CamposValores")
                        .HasForeignKey("CampoArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("CampoArticulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", "TipoArticulo")
                        .WithMany("Campos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoArticulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Prestamos", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany("Prestamos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Mantenimiento.Entity.Mantenimientos", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Modulo", "Modulo")
                        .WithMany("SubModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Usuario", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Security.RolPermisos", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId");

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Roles", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("SubModuloId");

                    b.Navigation("Modulo");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Traslados.Entities.Traslado", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("UbicacionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "UbicacionOrigen")
                        .WithMany()
                        .HasForeignKey("UbicacionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("UbicacionDestino");

                    b.Navigation("UbicacionOrigen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "Padre")
                        .WithMany("Hijos")
                        .HasForeignKey("PadreId");

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.TipoUbicacion", "TipoUbicacion")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("TipoUbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Padre");

                    b.Navigation("TipoUbicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", b =>
                {
                    b.Navigation("CamposValores");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Campos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Modulo", b =>
                {
                    b.Navigation("SubModulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Roles", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.TipoUbicacion", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Hijos");
                });
#pragma warning restore 612, 618
        }
    }
}
