// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_de_practicas.Data;

#nullable disable

namespace Proyecto_de_practicas.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20260716074149_AddDocumentoFirmaToTraslado")]
    partial class AddDocumentoFirmaToTraslado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClasificacionDepreciacionId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPatrimonial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DepreciacionAnual")
                        .HasColumnType("float");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAdquision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtrasObservaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TiempoVidaUtil")
                        .HasColumnType("float");

                    b.Property<int>("TipoArticuloId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("ValorAdquisitivo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClasificacionDepreciacionId");

                    b.HasIndex("TipoArticuloId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Articulos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoPatrimonial = "UNSM-001",
                            Condicion = "Bueno",
                            DepreciacionAnual = 20.0,
                            Estado = 1,
                            FechaAdquision = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "HP",
                            Modelo = "ProDesk 400 G7",
                            Nombre = "Computadora de Escritorio HP",
                            NroSerie = "SN-HP-001",
                            TiempoVidaUtil = 5.0,
                            TipoArticuloId = 1,
                            UbicacionId = 100,
                            ValorActual = 2000.00m,
                            ValorAdquisitivo = 2500.0
                        },
                        new
                        {
                            Id = 2,
                            CodigoPatrimonial = "UNSM-002",
                            Condicion = "Bueno",
                            DepreciacionAnual = 10.0,
                            Estado = 1,
                            FechaAdquision = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Norditalia",
                            Modelo = "Ejecutiva-X",
                            Nombre = "Silla Ergonómica",
                            TiempoVidaUtil = 10.0,
                            TipoArticuloId = 2,
                            UbicacionId = 100,
                            ValorActual = 315.00m,
                            ValorAdquisitivo = 350.0
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.ArticuloCampoValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("CampoArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("CampoArticuloId");

                    b.ToTable("ArticuloCamposValores");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoArticuloId");

                    b.ToTable("CamposArticulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.ClasificacionDepreciacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PorcentajeDepreciacionAnual")
                        .HasColumnType("float");

                    b.Property<double>("VidaUtilAnios")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ClasificacionesDepreciacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.EncabezadoResult", b =>
                {
                    b.Property<string>("Encabezado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EncabezadoResult");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Prestamos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobar")
                        .HasColumnType("bit");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoPrestamo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImagenPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoArticulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Computadoras personales de escritorio, computadoras protales, computadores personales todo (AIO), Estaciones de trabajo, Thin Client, Tablets",
                            Estado = 1,
                            ImagenPath = "/",
                            Nombre = "Equipo de computo personal"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Sillas, mesas y mobiliario de oficina",
                            Estado = 1,
                            ImagenPath = "/",
                            Nombre = "Impresoras & Escaner"
                        },
                        new
                        {
                            Id = 100,
                            Descripcion = "Otros",
                            Estado = 1,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Mantenimiento.Entity.Mantenimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoMantenimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorServicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Notificaciones.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioDestinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Icon = "fa-solid fa-home",
                            Nombre = "Dashboard",
                            Ruta = "/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Icon = "fa-solid fa-box",
                            Nombre = "Artículos",
                            Ruta = "/articulos"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            Icon = "fa-solid fa-map-marker-alt",
                            Nombre = "Ubicaciones",
                            Ruta = "/ubicaciones"
                        },
                        new
                        {
                            Id = 4,
                            Estado = 1,
                            Icon = "fa-solid fa-exchange-alt",
                            Nombre = "Traslados",
                            Ruta = "/traslados"
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            Icon = "fa-solid fa-handshake",
                            Nombre = "Prestamos",
                            Ruta = "/prestamos"
                        },
                        new
                        {
                            Id = 6,
                            Estado = 1,
                            Icon = "fa-solid fa-screwdriver-wrench",
                            Nombre = "Mantenimiento",
                            Ruta = "/mantenimiento"
                        },
                        new
                        {
                            Id = 7,
                            Estado = 1,
                            Icon = "fa-solid fa-chart-line",
                            Nombre = "Reportes",
                            Ruta = "/reportes"
                        },
                        new
                        {
                            Id = 8,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            Nombre = "Seguridad",
                            Ruta = "/seguridad"
                        },
                        new
                        {
                            Id = 9,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            Nombre = "Gestion institucional",
                            Ruta = "/gestion-institucional"
                        },
                        new
                        {
                            Id = 10,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            Nombre = "Inventario",
                            Ruta = "/inventario"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Crear"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Editar"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Ver"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Eliminar"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Nombre = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            Nombre = "Tecnico"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("SubModulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            Icon = "fa-solid fa-box-open",
                            ModuloId = 2,
                            Nombre = "Artículos",
                            Ruta = "/articulos"
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Icon = "fa-solid fa-tags",
                            ModuloId = 2,
                            Nombre = "Tipos de Artículo",
                            Ruta = "/tipos-articulos"
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            Icon = "fa-solid fa-map-marker",
                            ModuloId = 3,
                            Nombre = "Ubicaciones",
                            Ruta = "/ubicaciones"
                        },
                        new
                        {
                            Id = 4,
                            Estado = 1,
                            Icon = "fa-solid fa-layer-group",
                            ModuloId = 3,
                            Nombre = "Tipos de Ubicación",
                            Ruta = "/tipo-ubicacion"
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            Icon = "fa-solid fa-user",
                            ModuloId = 8,
                            Nombre = "Usuarios",
                            Ruta = "/usuarios"
                        },
                        new
                        {
                            Id = 6,
                            Estado = 1,
                            Icon = "fa-solid fa-user-shield",
                            ModuloId = 8,
                            Nombre = "Roles",
                            Ruta = "/roles"
                        },
                        new
                        {
                            Id = 7,
                            Estado = 1,
                            Icon = "fa-solid fa-key",
                            ModuloId = 8,
                            Nombre = "Permisos",
                            Ruta = "/permisos"
                        },
                        new
                        {
                            Id = 8,
                            Estado = 1,
                            Icon = "fa-solid fa-layer-group",
                            ModuloId = 8,
                            Nombre = "Modulos",
                            Ruta = "/modulos"
                        },
                        new
                        {
                            Id = 9,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            ModuloId = 3,
                            Nombre = "Sedes",
                            Ruta = "/sedes"
                        },
                        new
                        {
                            Id = 10,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            ModuloId = 3,
                            Nombre = "Facultades",
                            Ruta = "/facultades"
                        },
                        new
                        {
                            Id = 11,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            ModuloId = 3,
                            Nombre = "Escuelas",
                            Ruta = "/escuelas"
                        },
                        new
                        {
                            Id = 12,
                            Estado = 1,
                            Icon = "fa-solid fa-shield-alt",
                            ModuloId = 5,
                            Nombre = "Prestamos",
                            Ruta = "/prestamos"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Security.RolPermisos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int?>("SubModuloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.HasIndex("SubModuloId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 6,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 7,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 8,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 9,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 10,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 11,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 12,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 13,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 14,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 15,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 16,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 4
                        },
                        new
                        {
                            Id = 17,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 18,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 19,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 20,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 5
                        },
                        new
                        {
                            Id = 21,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 22,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 23,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 24,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 6
                        },
                        new
                        {
                            Id = 25,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 26,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 27,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 28,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 7
                        },
                        new
                        {
                            Id = 29,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 30,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 31,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 32,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 8
                        },
                        new
                        {
                            Id = 37,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 9
                        },
                        new
                        {
                            Id = 38,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 9
                        },
                        new
                        {
                            Id = 39,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 9
                        },
                        new
                        {
                            Id = 40,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 9
                        },
                        new
                        {
                            Id = 41,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 10
                        },
                        new
                        {
                            Id = 42,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 10
                        },
                        new
                        {
                            Id = 43,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 10
                        },
                        new
                        {
                            Id = 44,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 10
                        },
                        new
                        {
                            Id = 45,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 11
                        },
                        new
                        {
                            Id = 46,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 11
                        },
                        new
                        {
                            Id = 47,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 11
                        },
                        new
                        {
                            Id = 48,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 11
                        },
                        new
                        {
                            Id = 49,
                            PermisoId = 1,
                            RolId = 1,
                            SubModuloId = 12
                        },
                        new
                        {
                            Id = 50,
                            PermisoId = 2,
                            RolId = 1,
                            SubModuloId = 12
                        },
                        new
                        {
                            Id = 51,
                            PermisoId = 3,
                            RolId = 1,
                            SubModuloId = 12
                        },
                        new
                        {
                            Id = 52,
                            PermisoId = 4,
                            RolId = 1,
                            SubModuloId = 12
                        },
                        new
                        {
                            Id = 53,
                            ModuloId = 4,
                            PermisoId = 1,
                            RolId = 1
                        },
                        new
                        {
                            Id = 54,
                            ModuloId = 4,
                            PermisoId = 2,
                            RolId = 1
                        },
                        new
                        {
                            Id = 55,
                            ModuloId = 4,
                            PermisoId = 3,
                            RolId = 1
                        },
                        new
                        {
                            Id = 56,
                            ModuloId = 4,
                            PermisoId = 4,
                            RolId = 1
                        },
                        new
                        {
                            Id = 57,
                            ModuloId = 6,
                            PermisoId = 1,
                            RolId = 1
                        },
                        new
                        {
                            Id = 58,
                            ModuloId = 6,
                            PermisoId = 2,
                            RolId = 1
                        },
                        new
                        {
                            Id = 59,
                            ModuloId = 6,
                            PermisoId = 3,
                            RolId = 1
                        },
                        new
                        {
                            Id = 60,
                            ModuloId = 6,
                            PermisoId = 4,
                            RolId = 1
                        },
                        new
                        {
                            Id = 61,
                            ModuloId = 7,
                            PermisoId = 1,
                            RolId = 1
                        },
                        new
                        {
                            Id = 62,
                            ModuloId = 7,
                            PermisoId = 2,
                            RolId = 1
                        },
                        new
                        {
                            Id = 63,
                            ModuloId = 7,
                            PermisoId = 3,
                            RolId = 1
                        },
                        new
                        {
                            Id = 64,
                            ModuloId = 7,
                            PermisoId = 4,
                            RolId = 1
                        },
                        new
                        {
                            Id = 65,
                            ModuloId = 9,
                            PermisoId = 1,
                            RolId = 1
                        },
                        new
                        {
                            Id = 66,
                            ModuloId = 9,
                            PermisoId = 2,
                            RolId = 1
                        },
                        new
                        {
                            Id = 67,
                            ModuloId = 9,
                            PermisoId = 3,
                            RolId = 1
                        },
                        new
                        {
                            Id = 68,
                            ModuloId = 9,
                            PermisoId = 4,
                            RolId = 1
                        },
                        new
                        {
                            Id = 69,
                            ModuloId = 10,
                            PermisoId = 1,
                            RolId = 1
                        },
                        new
                        {
                            Id = 70,
                            ModuloId = 10,
                            PermisoId = 2,
                            RolId = 1
                        },
                        new
                        {
                            Id = 71,
                            ModuloId = 10,
                            PermisoId = 3,
                            RolId = 1
                        },
                        new
                        {
                            Id = 72,
                            ModuloId = 10,
                            PermisoId = 4,
                            RolId = 1
                        },
                        new
                        {
                            Id = 33,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 1
                        },
                        new
                        {
                            Id = 34,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 2
                        },
                        new
                        {
                            Id = 35,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 3
                        },
                        new
                        {
                            Id = 36,
                            PermisoId = 3,
                            RolId = 2,
                            SubModuloId = 4
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Traslados.Entities.Traslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTraslado")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UbicacionDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionOrigenId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UbicacionDestinoId");

                    b.HasIndex("UbicacionOrigenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Traslado");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Escuelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultadId = 1,
                            Nombre = "Ingeniería de Sistemas e Informática"
                        },
                        new
                        {
                            Id = 2,
                            FacultadId = 2,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Id = 3,
                            FacultadId = 2,
                            Nombre = "Administración"
                        },
                        new
                        {
                            Id = 4,
                            FacultadId = 3,
                            Nombre = "Ingeniería Agroindustrial"
                        },
                        new
                        {
                            Id = 5,
                            FacultadId = 4,
                            Nombre = "Educación Primaria"
                        },
                        new
                        {
                            Id = 6,
                            FacultadId = 2,
                            Nombre = "Economía"
                        },
                        new
                        {
                            Id = 7,
                            FacultadId = 2,
                            Nombre = "Turismo"
                        },
                        new
                        {
                            Id = 8,
                            FacultadId = 4,
                            Nombre = "Educación Inicial"
                        },
                        new
                        {
                            Id = 9,
                            FacultadId = 4,
                            Nombre = "Educación Secundaria"
                        },
                        new
                        {
                            Id = 10,
                            FacultadId = 4,
                            Nombre = "Idiomas"
                        },
                        new
                        {
                            Id = 11,
                            FacultadId = 4,
                            Nombre = "Psicología"
                        },
                        new
                        {
                            Id = 12,
                            FacultadId = 5,
                            Nombre = "Agronomía"
                        },
                        new
                        {
                            Id = 13,
                            FacultadId = 5,
                            Nombre = "Medicina Veterinaria"
                        },
                        new
                        {
                            Id = 14,
                            FacultadId = 6,
                            Nombre = "Enfermería"
                        },
                        new
                        {
                            Id = 15,
                            FacultadId = 6,
                            Nombre = "Obstetricia"
                        },
                        new
                        {
                            Id = 16,
                            FacultadId = 7,
                            Nombre = "Derecho"
                        },
                        new
                        {
                            Id = 17,
                            FacultadId = 8,
                            Nombre = "Ingeniería Ambiental"
                        },
                        new
                        {
                            Id = 18,
                            FacultadId = 8,
                            Nombre = "Ingeniería Sanitaria"
                        },
                        new
                        {
                            Id = 19,
                            FacultadId = 9,
                            Nombre = "Arquitectura"
                        },
                        new
                        {
                            Id = 20,
                            FacultadId = 9,
                            Nombre = "Ingeniería Civil"
                        },
                        new
                        {
                            Id = 21,
                            FacultadId = 10,
                            Nombre = "Medicina Humana"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Facultades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SedeId");

                    b.ToTable("Facultades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Ingeniería de Sistemas e Informática",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Ciencias Económicas",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Ingeniería Agroindustrial",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Educación y Humanidades",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Ciencias Agrarias",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 6,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Ciencias de la Salud",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 7,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Derecho y Ciencias Políticas",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 8,
                            Direccion = "Prolongación 20 de Abril S/N (Cuadra 3, Barrio Calvario), Moyobamba",
                            Estado = true,
                            Nombre = "Facultad de Ecología",
                            SedeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Ingeniería Civil y Arquitectura",
                            SedeId = 4
                        },
                        new
                        {
                            Id = 10,
                            Direccion = "Ciudad Universitaria, Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Facultad de Medicina Humana",
                            SedeId = 4
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Sedes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sedes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Jr. Santo Toribio N° 1200 ",
                            Estado = true,
                            Nombre = "Rioja"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Prolongación 20 de Abril S/N (Cuadra 3, Barrio Calvario)",
                            Estado = true,
                            Nombre = "Moyobamba"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Jr. Reynaldo Bartra S/N, Lamas",
                            Estado = true,
                            Nombre = "Lamas"
                        },
                        new
                        {
                            Id = 4,
                            Direccion = " Jr. Amorarca N° 334, Morales",
                            Estado = true,
                            Nombre = "Morales"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.TipoUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUbicacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Aulas de clase presencial",
                            Nombre = "Aula"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Laboratorios de cómputo y ciencias",
                            Nombre = "Laboratorio"
                        },
                        new
                        {
                            Id = 100,
                            Descripcion = "Ubicación general sin clasificar",
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EscuelaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<int>("TipoUbicacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.HasIndex("TipoUbicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ubicaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Aula de clases piso 1",
                            EscuelaId = 1,
                            Nombre = "Aula 101",
                            Piso = 1,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Aula de clases piso 1",
                            EscuelaId = 1,
                            Nombre = "Aula 102",
                            Piso = 1,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Aula de clases piso 1",
                            EscuelaId = 1,
                            Nombre = "Aula 103",
                            Piso = 1,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Aula de clases piso 2",
                            EscuelaId = 1,
                            Nombre = "Aula 201",
                            Piso = 2,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Aula de clases piso 2",
                            EscuelaId = 1,
                            Nombre = "Aula 202",
                            Piso = 2,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Aula de clases piso 2",
                            EscuelaId = 2,
                            Nombre = "Aula 203",
                            Piso = 2,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Aula de clases piso 3",
                            EscuelaId = 2,
                            Nombre = "Aula 301",
                            Piso = 3,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Aula de clases piso 3",
                            EscuelaId = 2,
                            Nombre = "Aula 302",
                            Piso = 3,
                            TipoUbicacionId = 1
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Lab. de redes y comunicaciones",
                            EscuelaId = 1,
                            Nombre = "Laboratorio de Redes",
                            Piso = 1,
                            TipoUbicacionId = 2
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Lab. de programación básica",
                            EscuelaId = 1,
                            Nombre = "Laboratorio de Programación I",
                            Piso = 1,
                            TipoUbicacionId = 2
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Lab. de programación avanzada",
                            EscuelaId = 1,
                            Nombre = "Laboratorio de Programación II",
                            Piso = 2,
                            TipoUbicacionId = 2
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Lab. de bases de datos y SQL",
                            EscuelaId = 1,
                            Nombre = "Laboratorio de Base de Datos",
                            Piso = 2,
                            TipoUbicacionId = 2
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Lab. de mantenimiento de equipos",
                            EscuelaId = 1,
                            Nombre = "Laboratorio de Hardware",
                            Piso = 3,
                            TipoUbicacionId = 2
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Lab. de ciencias básicas",
                            EscuelaId = 3,
                            Nombre = "Laboratorio de Ciencias",
                            Piso = 1,
                            TipoUbicacionId = 2
                        },
                        new
                        {
                            Id = 100,
                            Descripcion = "Ubicación por defecto para artículos sin ubicación especificada",
                            Nombre = "Otros",
                            Piso = 0,
                            TipoUbicacionId = 100
                        });
                });

            modelBuilder.Entity("Solicitantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Solicitantes");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.ClasificacionDepreciacion", "ClasificacionDepreciacion")
                        .WithMany("Articulos")
                        .HasForeignKey("ClasificacionDepreciacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", "TipoArticulo")
                        .WithMany("Articulos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Articulos")
                        .HasForeignKey("UbicacionId");

                    b.Navigation("ClasificacionDepreciacion");

                    b.Navigation("TipoArticulo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.ArticuloCampoValor", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", "CampoArticulo")
                        .WithMany("CamposValores")
                        .HasForeignKey("CampoArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("CampoArticulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", "TipoArticulo")
                        .WithMany("Campos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoArticulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Prestamos", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany("Prestamos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Solicitantes", "Solicitante")
                        .WithMany("Prestamo")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Mantenimiento.Entity.Mantenimientos", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Modulo", "Modulo")
                        .WithMany("SubModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Usuario", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Security.RolPermisos", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId");

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Roles", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("SubModuloId");

                    b.Navigation("Modulo");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Traslados.Entities.Traslado", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("UbicacionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "UbicacionOrigen")
                        .WithMany()
                        .HasForeignKey("UbicacionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("UbicacionDestino");

                    b.Navigation("UbicacionOrigen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Escuelas", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Facultades", "Facultad")
                        .WithMany("Escuelas")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facultad");

                    b.Navigation("Tecnico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Facultades", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Sedes", "Sede")
                        .WithMany("Facultades")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Escuelas", "Escuela")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.TipoUbicacion", "TipoUbicacion")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("TipoUbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_de_practicas.Modules.Security.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Escuela");

                    b.Navigation("TipoUbicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Solicitantes", b =>
                {
                    b.HasOne("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Solicitantes")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.Articulo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.CampoArticulo", b =>
                {
                    b.Navigation("CamposValores");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.ClasificacionDepreciacion", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Articulos.Entities.TipoArticulo", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Campos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Modulo", b =>
                {
                    b.Navigation("SubModulos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Security.Entities.Roles", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Escuelas", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Facultades", b =>
                {
                    b.Navigation("Escuelas");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Sedes", b =>
                {
                    b.Navigation("Facultades");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.TipoUbicacion", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Proyecto_de_practicas.Modules.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Solicitantes");
                });

            modelBuilder.Entity("Solicitantes", b =>
                {
                    b.Navigation("Prestamo");
                });
#pragma warning restore 612, 618
        }
    }
}
